// SPDX-License-Identifier: MIT OR Apache-2.0
// ---------------------------------------------------------------------------
// Request types
// ---------------------------------------------------------------------------

export interface VerifyPassportRequest {
  /** Attestation identifier from the ePassport scan. */
  attestation_id: string;
  /** ZK proof object generated by the client. */
  proof: Record<string, unknown>;
  /** Public signals accompanying the proof. */
  pub_signals: Record<string, unknown>;
  /** Optional client-side context (device info, locale, etc.). */
  userContextData?: Record<string, unknown>;
}

export interface AttachCommitmentRequest {
  /** Semaphore identity commitment (bigint as string). */
  commitment: string;
}

export interface AnonymousVoteRequest {
  /** On-chain proposal identifier. */
  proposalId: string;
  /** Selected voting option. */
  optionId: string;
  /** Semaphore ZK proof. */
  proof: Record<string, unknown>;
  /** Proof nullifier to prevent double-voting. */
  nullifier: string;
  /** Signal broadcast with the proof. */
  signal: string;
  /** External nullifier scoped to the proposal. */
  externalNullifier: string;
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

export interface VerifyPassportResponse {
  /** Unique nullifier derived from the proof. */
  nullifier: string;
  /** Assigned trust tier based on verification strength. */
  trustTier: string;
  /** ISO-8601 timestamp of verification. */
  verifiedAt: string;
}

export interface AttachCommitmentResponse {
  success: boolean;
  /** The commitment that was attached. */
  commitment: string;
}

export interface GroupResponse {
  /** List of Semaphore identity commitments in the group. */
  commitments: string[];
  /** Total members in the group. */
  memberCount: number;
  /** Current Merkle root of the Semaphore group. */
  merkleRoot: string;
}

export interface AnonymousVoteResponse {
  success: boolean;
  /** Solana transaction signature. */
  transactionSignature: string;
}

export interface StatusResponse {
  /** Whether a record exists for this nullifier. */
  exists: boolean;
  nullifier: string;
  /** Type of proof used (present only when exists is true). */
  proofType?: string;
  /** Trust tier (present only when exists is true). */
  trustTier?: string;
  /** Verification timestamp (present only when exists is true). */
  verifiedAt?: string;
  /** Whether a Semaphore commitment is bound to this identity. */
  hasCommitment: boolean;
}

// ---------------------------------------------------------------------------
// Client options
// ---------------------------------------------------------------------------

export interface PohClientOptions {
  /** Base URL of your verification-API deployment (required — no public default). */
  baseUrl: string;
}
